import { NextRequest, NextResponse } from 'next/server';
import { deductCredits, getCredits } from '@/lib/credits';

export async function POST(request: NextRequest) {
  try {
    const { text, userId = 'demo-user' } = await request.json();

    if (!text) {
      return NextResponse.json(
        { error: 'Text is required' },
        { status: 400 }
      );
    }

    // Check credits
    const currentCredits = getCredits(userId);
    if (currentCredits < 2) {
      return NextResponse.json(
        { error: 'Insufficient credits. Need 2 credits to generate a meme.' },
        { status: 402 }
      );
    }

    // Deduct credits
    const success = deductCredits(userId, 2);
    if (!success) {
      return NextResponse.json(
        { error: 'Failed to deduct credits' },
        { status: 500 }
      );
    }

    // Split text into top and bottom parts
    const textParts = text.split('|');
    const topText = textParts[0]?.trim() || '';
    const bottomText = textParts[1]?.trim() || '';

    // Generate meme data (server-side simplified version)
    const memeResponse = {
      imageData: await generateServerMeme(topText, bottomText),
      altText: `Meme with text: "${topText}" and "${bottomText}"`,
      width: 500,
      height: 500,
      creditsRemaining: getCredits(userId)
    };

    return NextResponse.json(memeResponse);
  } catch (error) {
    console.error('Error generating meme:', error);
    return NextResponse.json(
      { error: 'Failed to generate meme' },
      { status: 500 }
    );
  }
}

async function generateServerMeme(topText: string, bottomText: string): Promise<string> {
  // For demo purposes, return a base64 encoded SVG as PNG
  const svg = `
    <svg width="500" height="500" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="bg" x1="0%" y1="0%" x2="0%" y2="100%">
          <stop offset="0%" style="stop-color:#8B5CF6;stop-opacity:1" />
          <stop offset="100%" style="stop-color:#3B82F6;stop-opacity:1" />
        </linearGradient>
      </defs>
      <rect width="500" height="500" fill="url(#bg)" stroke="#fff" stroke-width="4"/>
      <text x="250" y="100" text-anchor="middle" font-family="Arial, sans-serif" font-size="36" font-weight="bold" fill="#fff" stroke="#000" stroke-width="2">${topText.toUpperCase()}</text>
      <text x="250" y="400" text-anchor="middle" font-family="Arial, sans-serif" font-size="36" font-weight="bold" fill="#fff" stroke="#000" stroke-width="2">${bottomText.toUpperCase()}</text>
      <text x="490" y="490" text-anchor="end" font-family="Arial, sans-serif" font-size="12" fill="rgba(255,255,255,0.7)">Generated by Meme Bot Pro</text>
    </svg>
  `;
  
  return `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`;
}